export const dopplerHookAbi = [
  {
    type: 'function',
    name: 'state',
    inputs: [],
    outputs: [
      { name: 'lastEpoch', type: 'uint40' },
      { name: 'tickAccumulator', type: 'int256' },
      { name: 'totalTokensSold', type: 'uint256' },
      { name: 'totalProceeds', type: 'uint256' },
      { name: 'totalTokensSoldLastEpoch', type: 'uint256' },
      { name: 'feesAccrued', type: 'int256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'earlyExit',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'insufficientProceeds',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'poolKey',
    inputs: [],
    outputs: [
      { name: 'currency0', type: 'address' },
      { name: 'currency1', type: 'address' },
      { name: 'fee', type: 'uint24' },
      { name: 'tickSpacing', type: 'int24' },
      { name: 'hooks', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'startingTime',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'endingTime',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'epochLength',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'minimumProceeds',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maximumProceeds',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'numTokensToSell',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'startingTick',
    inputs: [],
    outputs: [{ name: '', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'endingTick',
    inputs: [],
    outputs: [{ name: '', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'gamma',
    inputs: [],
    outputs: [{ name: '', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isToken0',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'numPDSlugs',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  { type: 'error', name: 'InvalidGamma', inputs: [] },
  { type: 'error', name: 'InvalidTimeRange', inputs: [] },
  { type: 'error', name: 'CannotAddLiquidity', inputs: [] },
  { type: 'error', name: 'CannotSwapBeforeStartTime', inputs: [] },
  { type: 'error', name: 'SwapBelowRange', inputs: [] },
  { type: 'error', name: 'InvalidStartTime', inputs: [] },
  { type: 'error', name: 'InvalidTickRange', inputs: [] },
  { type: 'error', name: 'InvalidTickSpacing', inputs: [] },
  { type: 'error', name: 'InvalidEpochLength', inputs: [] },
  { type: 'error', name: 'InvalidProceedLimits', inputs: [] },
  { type: 'error', name: 'InvalidNumPDSlugs', inputs: [] },
  {
    type: 'error',
    name: 'InvalidSwapAfterMaturitySufficientProceeds',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidSwapAfterMaturityInsufficientProceeds',
    inputs: [],
  },
  { type: 'error', name: 'MaximumProceedsReached', inputs: [] },
  { type: 'error', name: 'SenderNotPoolManager', inputs: [] },
  { type: 'error', name: 'AlreadyInitialized', inputs: [] },
  { type: 'error', name: 'SenderNotInitializer', inputs: [] },
  { type: 'error', name: 'CannotMigrate', inputs: [] },
  { type: 'error', name: 'CannotDonate', inputs: [] },
] as const;
