export const v4MulticurveInitializerAbi = [
  {
    type: 'function',
    name: 'airlock',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract Airlock' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'HOOK',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IHooks' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'collectFees',
    inputs: [{ name: 'poolId', type: 'bytes32', internalType: 'PoolId' }],
    outputs: [
      { name: 'fees0', type: 'uint128', internalType: 'uint128' },
      { name: 'fees1', type: 'uint128', internalType: 'uint128' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getState',
    inputs: [{ name: 'asset', type: 'address', internalType: 'address' }],
    outputs: [
      { name: 'numeraire', type: 'address', internalType: 'address' },
      { name: 'status', type: 'uint8', internalType: 'enum PoolStatus' },
      {
        name: 'poolKey',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          { name: 'currency0', type: 'address', internalType: 'Currency' },
          { name: 'currency1', type: 'address', internalType: 'Currency' },
          { name: 'fee', type: 'uint24', internalType: 'uint24' },
          { name: 'tickSpacing', type: 'int24', internalType: 'int24' },
          { name: 'hooks', type: 'address', internalType: 'contract IHooks' },
        ],
      },
      { name: 'farTick', type: 'int24', internalType: 'int24' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'Collect',
    inputs: [
      { name: 'pool', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'beneficiary',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'fees0',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'fees1',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Create',
    inputs: [
      {
        name: 'poolOrHook',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'asset',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'numeraire',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Lock',
    inputs: [
      { name: 'pool', type: 'address', indexed: true, internalType: 'address' },
      {
        name: 'beneficiaries',
        type: 'tuple[]',
        indexed: false,
        internalType: 'struct BeneficiaryData[]',
        components: [
          { name: 'beneficiary', type: 'address', internalType: 'address' },
          { name: 'shares', type: 'uint96', internalType: 'uint96' },
        ],
      },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'PoolLocked', inputs: [] },
  { type: 'error', name: 'PoolNotLocked', inputs: [] },
  { type: 'error', name: 'PoolAlreadyInitialized', inputs: [] },
  { type: 'error', name: 'PoolAlreadyExited', inputs: [] },
  {
    type: 'error',
    name: 'CannotMigrateInsufficientTick',
    inputs: [
      { name: 'targetTick', type: 'int24', internalType: 'int24' },
      { name: 'currentTick', type: 'int24', internalType: 'int24' },
    ],
  },
  { type: 'error', name: 'SenderNotAirlock', inputs: [] },
  { type: 'error', name: 'UnorderedBeneficiaries', inputs: [] },
  { type: 'error', name: 'InvalidShares', inputs: [] },
  { type: 'error', name: 'InvalidTotalShares', inputs: [] },
  { type: 'error', name: 'InvalidProtocolOwnerShares', inputs: [] },
  { type: 'error', name: 'InvalidProtocolOwnerBeneficiary', inputs: [] },
] as const;
