name: "Deploy to environment"
description: "Deploy to environment"

# THIS ACTION IS NOT MEANT TO BE RUN INDEPENDENTLY
# IT WILL BE UTILIZED WITH "uses" FIELD IN ".github" FOLDER
# THIS ACTION ASSUMES CI HAS BEEN RUN AND CODE IS VALID

inputs:
  repo:
    description: "Name of the repository to deploy"
    required: true

  env:
    description: "Environment to deploy to"
    required: true

  bump:
    description: "How to bump the version (required for stage only)"
    required: false
    default: "patch"

runs:
  using: composite
  steps:
    - name: Configure Git
      run: |
        git config --local user.name 'whetstone-research[bot]'
        git config --local user.email 'whetstone-research[bot]@users.noreply.github.com'
      shell: bash

    - name: Bump/document version
      if: inputs.env == 'dev'
      run: |
        if [ "${{ inputs.bump }}" = "" ]; then 
          echo "Error: Bump version is required for dev environment" >&2
          exit 1
        fi
        cd packages/${{ inputs.repo }}
        pnpm version ${{ inputs.bump }}
        git push origin main
      shell: bash

    - name: Update deployed/${{ inputs.env }} branch
      run: |
        git fetch
        git checkout deployed/${{ inputs.env }}
        if [ "${{ inputs.env }}" = "dev" ]; then
          git merge main --ff-only
        elif [ "${{ inputs.env }}" = "stage" ]; then
          git merge deployed/dev --ff-only
        elif [ "${{ inputs.env }}" = "prod" ]; then
          git merge deployed/stage --ff-only
        fi
      shell: bash
    
    # - name: Publish to npm
    #   run: |
    #     cd packages/${{ inputs.repo }}
    #     if [ "${{ inputs.environment }}" == "dev" ]; then
    #       pnpm publish:beta
    #     elif [ "${{ inputs.environment }}" == "stage" ]; then
    #       pnpm publish:rc
    #     elif [ "${{ inputs.environment }}" == "prod" ]; then
    #       pnpm publish:latest
    #     else
    #       echo "Invalid environment specified"
    #       exit 1
    #     fi
