services:
  doppler-indexer-database:
    image: postgres:16.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: default
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
